# Generated by Django 5.2.7 on 2025-12-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_customers_is_exported_and_more'),
        ('client_management', '0001_initial'),
        ('master', '0002_whatsappdata_whatsappresponse'),
        ('product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='RequestTypeMaster',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(blank=True, max_length=50, null=True)),
                ('request_name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('request_name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(default=0, max_length=20)),
                ('subcategory', models.CharField(default=0, max_length=20)),
                ('complaint', models.CharField(max_length=500)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=50)),
                ('phone_no', models.CharField(default=0, max_length=50)),
                ('building_name', models.CharField(default=0, max_length=50)),
                ('room_or_flat_no', models.CharField(default=0, max_length=50)),
                ('floor_no', models.CharField(default=0, max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=100, null=True)),
                ('no_of_5g_bottles_required', models.IntegerField(default=0)),
                ('visit_schedule', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('emirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.emiratemaster')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.locationmaster')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('cancel', 'Cancel')], default='new', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to='accounts.customers')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_care.customerrequesttype')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestCancelReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(default=0, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_care.customerrequests')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('cancel', 'Cancel')], default='new', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_care.customerrequests')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='DiffBottlesModel',
            fields=[
                ('diffbottles_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.IntegerField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('custody', 'Custody'), ('paid', 'Paid')], max_length=10)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_net_total', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('assign_this_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bottles', to='accounts.customers')),
                ('product_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='OtherRequirementModel',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement', models.TextField(max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_otherrequirement', to='accounts.customers')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_care.requesttypemaster')),
            ],
            options={
                'ordering': ('request_type',),
            },
        ),
        migrations.CreateModel(
            name='CustodyPullOutModel',
            fields=[
                ('custodypullout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_to_be_taken_out', models.IntegerField(default=0)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_custodypullout', to='accounts.customers')),
                ('customer_custody_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_custody_item', to='client_management.custodycustomitems')),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_product', to='product.product')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_care.requesttypemaster')),
            ],
            options={
                'ordering': ('item_name',),
            },
        ),
        migrations.CreateModel(
            name='CouponPurchaseModel',
            fields=[
                ('couponpurchase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_type', models.CharField(choices=[('manual', 'Manual'), ('digital', 'Digital')], max_length=10)),
                ('category', models.CharField(choices=[('cash', 'Cash Coupon'), ('credit', 'Credit Coupon')], max_length=10)),
                ('number_of_books', models.IntegerField(null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('free_coupon', models.IntegerField(default=0)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_couponpurchase', to='accounts.customers')),
                ('request_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_care.requesttypemaster')),
            ],
            options={
                'ordering': ('request_type',),
            },
        ),
    ]
