# Generated by Django 5.2 on 2025-04-16 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignStaffCoupon',
            fields=[
                ('assign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alloted_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('remaining_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Closed', 'Closed')], max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('coupon_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_type_name', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_leaflets', models.CharField(blank=True, max_length=20, null=True)),
                ('valuable_leaflets', models.CharField(blank=True, max_length=20, null=True)),
                ('free_leaflets', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('coupon_type_name',),
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_num', models.CharField(blank=True, max_length=20, null=True)),
                ('value_starting_no', models.CharField(blank=True, max_length=20, null=True)),
                ('value_ending_no', models.CharField(blank=True, max_length=20, null=True)),
                ('free_starting_no', models.CharField(blank=True, max_length=20, null=True)),
                ('free_ending_no', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('coupon_method', models.CharField(blank=True, choices=[('digital', 'Digital'), ('manual', 'Manual')], default='manual', max_length=10, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_login', to='master.branchmaster')),
                ('coupon_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_type', to='coupon_management.coupontype')),
            ],
            options={
                'ordering': ('book_num',),
            },
        ),
        migrations.CreateModel(
            name='AssignStaffCouponDetails',
            fields=[
                ('assign_coupon_details_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Assigned to Staff', 'Assigned to Staff'), ('Assigned To Customer', 'Assigned To Customer')], max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('staff_coupon_assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_staff_coupon_request', to='coupon_management.assignstaffcoupon')),
                ('to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_customer', to='accounts.customers')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_coupon', to='coupon_management.coupon')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CouponRequest',
            fields=[
                ('coupon_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_user', to='master.branchmaster')),
                ('coupon_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_request', to='coupon_management.coupontype')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.AddField(
            model_name='assignstaffcoupon',
            name='coupon_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_request_request', to='coupon_management.couponrequest'),
        ),
        migrations.CreateModel(
            name='NewCoupon',
            fields=[
                ('coupon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_num', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_leaflets', models.CharField(blank=True, max_length=20, null=True)),
                ('valuable_leaflets', models.CharField(blank=True, max_length=20, null=True)),
                ('free_leaflets', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('coupon_method', models.CharField(blank=True, choices=[('digital', 'Digital'), ('manual', 'Manual')], default='manual', max_length=10, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='coupon_qr_codes')),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_login_id', to='master.branchmaster')),
                ('coupon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couponsType', to='coupon_management.coupontype')),
            ],
            options={
                'ordering': ('book_num',),
            },
        ),
        migrations.CreateModel(
            name='FreeLeaflet',
            fields=[
                ('couponleaflet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaflet_number', models.CharField(max_length=10)),
                ('leaflet_name', models.CharField(blank=True, max_length=20, null=True)),
                ('used', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='leaflet_qr_codes')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon_management.newcoupon')),
            ],
            options={
                'ordering': ('leaflet_number',),
            },
        ),
        migrations.CreateModel(
            name='CouponStock',
            fields=[
                ('couponstock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_stock', models.CharField(blank=True, choices=[('company', 'Company'), ('driver', 'Driver'), ('customer', 'Customer'), ('used', 'Used'), ('van', 'Van')], default='company', max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('couponbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couponbook_stock', to='coupon_management.newcoupon')),
            ],
            options={
                'ordering': ('-couponstock_id',),
            },
        ),
        migrations.CreateModel(
            name='CouponLeaflet',
            fields=[
                ('couponleaflet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaflet_number', models.CharField(max_length=10)),
                ('leaflet_name', models.CharField(blank=True, max_length=20, null=True)),
                ('used', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='leaflet_qr_codes')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaflets', to='coupon_management.newcoupon')),
            ],
            options={
                'ordering': ('leaflet_number',),
            },
        ),
    ]
