# Generated by Django 5.2.7 on 2025-12-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_customers_is_exported_and_more'),
        ('master', '0002_whatsappdata_whatsappresponse'),
        ('product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=200)),
                ('invoice_no', models.CharField(max_length=200)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('invoice_type', models.CharField(choices=[('cash_invoice', 'Cash Invoice'), ('credit_invoive', 'Credit Invoice')], default='cash_invoice', max_length=200)),
                ('invoice_status', models.CharField(choices=[('non_paid', 'Non Paid'), ('paid', 'Paid')], default='non_paid', max_length=200)),
                ('created_date', models.DateTimeField()),
                ('net_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amout_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amout_recieved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDailyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_management.invoice')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice Dialy Collection',
                'verbose_name_plural': 'Invoice Dialy Collection',
                'db_table': 'invoice_dialy_collection',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_including_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.categorymaster')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_management.invoice')),
                ('product_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'verbose_name': 'Invoice Items',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='SuspenseCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('cash_sale_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_sale_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payeble_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_no', models.CharField(max_length=200)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspense Collection',
                'verbose_name_plural': 'Suspense Collection',
                'db_table': 'suspense_collection',
            },
        ),
    ]
