# Generated by Django 5.2 on 2025-04-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_management', '0001_initial'),
        ('master', '0001_initial'),
        ('product', '0001_initial'),
        ('tax_settings', '0001_initial'),
        ('van_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nextdaystockrequest',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='van_management.van'),
        ),
        migrations.AddField(
            model_name='orderverifiedsupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderverifiedproductdetails',
            name='order_varified_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderverifiedsupervisor'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productiondamagereason'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_stock_branch', to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='produtitemmaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.categorymaster'),
        ),
        migrations.AddField(
            model_name='produtitemmaster',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_settings.tax'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='productexportstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_export_status', to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='product_default_price_level',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='orderverifiedproductdetails',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='nextdaystockrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_day_stock_request', to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='damagebottlestock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='scrapcleanedstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='scrapproductstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='scrapstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='coupon_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couponsales', to='coupon_management.newcoupon'),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_products', to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='salesman_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'designation_id__designation_name__in': ['Sales Executive', 'Sales Supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesman_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='van_management.van'),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='van_route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_route_orders', to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='orderverifiedsupervisor',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_supervisor_details', to='product.staff_orders'),
        ),
        migrations.AddField(
            model_name='staff_orders_details',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='staff_orders_details',
            name='staff_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_orders', to='product.staff_orders'),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='staff_Orders_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesman_order_details', to='product.staff_orders_details'),
        ),
        migrations.AddField(
            model_name='washedproducttransfer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='washedusedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='washingproductstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='washingstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
    ]
