# Generated by Django 4.0 on 2025-12-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('van_management', '0001_initial'),
        ('master', '0001_initial'),
        ('tax_settings', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_issueorders',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='van_management.van'),
        ),
        migrations.AddField(
            model_name='staff_issueorders',
            name='van_route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_route_orders', to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='scrapstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='scrapproductstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='scrapcleanedstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='produtitemmaster',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.categorymaster'),
        ),
        migrations.AddField(
            model_name='produtitemmaster',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax_settings.tax'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_stock_branch', to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productiondamagereason'),
        ),
        migrations.AddField(
            model_name='productiondamage',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='productexportstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_export_status', to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='product_default_price_level',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='orderverifiedsupervisor',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_supervisor_details', to='product.staff_orders'),
        ),
        migrations.AddField(
            model_name='orderverifiedsupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='orderverifiedproductdetails',
            name='order_varified_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderverifiedsupervisor'),
        ),
        migrations.AddField(
            model_name='orderverifiedproductdetails',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='nextdaystockrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_day_stock_request', to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='nextdaystockrequest',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='van_management.van'),
        ),
        migrations.AddField(
            model_name='damagebottlestock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
    ]
