# Generated by Django 5.2.7 on 2025-12-10 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_customers_is_exported_and_more'),
        ('master', '0002_whatsappdata_whatsappresponse'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_no', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
                ('net_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amout_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amout_recieved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason_for_return', models.TextField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Note',
                'db_table': 'credit_note',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_including_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.categorymaster')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_note.creditnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Credit Note Items',
                'verbose_name_plural': 'Credit Note Items',
                'db_table': 'credit_not_items',
            },
        ),
    ]
