# Generated by Django 5.2.7 on 2025-10-24 12:03

import ckeditor.fields
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(blank=True, choices=[('Branch User', 'Branch User'), ('Driver', 'Driver'), ('Salesman', 'Salesman'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Customer Care', 'Customer Care'), ('Accounts', 'Accounts'), ('store_keeper', 'Store Keeper'), ('marketing_executive', 'Marketing Executive'), ('Production', 'Production'), ('owner', 'Owner'), ('Driver cum Salesman', 'Driver cum Salesman')], max_length=50, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=16, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('labour_card_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('labour_card_expiry', models.DateTimeField(blank=True, null=True)),
                ('driving_licence_no', models.CharField(blank=True, max_length=1024, null=True)),
                ('driving_licence_expiry', models.DateTimeField(blank=True, null=True)),
                ('visa_no', models.CharField(blank=True, max_length=50, null=True)),
                ('visa_expiry', models.DateTimeField(blank=True, null=True)),
                ('emirates_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('emirates_expiry', models.DateTimeField(blank=True, null=True)),
                ('health_card_no', models.CharField(blank=True, max_length=50, null=True)),
                ('health_card_expiry', models.DateTimeField(blank=True, null=True)),
                ('base_salary', models.CharField(blank=True, max_length=50, null=True)),
                ('wps_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('wps_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry', models.DateTimeField(blank=True, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=50, null=True)),
                ('user_management', models.BooleanField(default=True)),
                ('product_management', models.BooleanField(default=True)),
                ('masters', models.BooleanField(default=True)),
                ('van_management', models.BooleanField(default=True)),
                ('coupon_management', models.BooleanField(default=True)),
                ('client_management', models.BooleanField(default=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('visa_type', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('passport_expiry', models.DateTimeField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Log',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('punch_in_date', models.DateField(auto_now_add=True, null=True)),
                ('punch_in_time', models.TimeField(auto_now=True, null=True)),
                ('punch_out_date', models.DateField(blank=True, null=True)),
                ('punch_out_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerPriceChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRateHistory',
            fields=[
                ('rate_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('new_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('custom_id', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('building_name', models.CharField(blank=True, max_length=250, null=True)),
                ('door_house_no', models.CharField(blank=True, max_length=250, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=250, null=True)),
                ('whats_app', models.CharField(blank=True, max_length=250, null=True)),
                ('email_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gps_latitude', models.CharField(default=0, max_length=100)),
                ('gps_longitude', models.CharField(default=0, max_length=100)),
                ('customer_type', models.CharField(blank=True, choices=[('HOME', 'HOME'), ('CORPORATE', 'CORPORATE'), ('WATCHMAN', 'WATCHMAN'), ('SHOP', 'SHOP')], max_length=100, null=True)),
                ('sales_type', models.CharField(blank=True, choices=[('CASH COUPON', 'CASH COUPON'), ('FOC', 'FOC'), ('CASH', 'CASH'), ('CREDIT', 'CREDIT')], max_length=100, null=True)),
                ('no_of_bottles_required', models.IntegerField(default=0)),
                ('max_credit_limit', models.IntegerField(default=0)),
                ('credit_days', models.IntegerField(default=0)),
                ('no_of_permitted_invoices', models.IntegerField(default=0)),
                ('trn', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visit_schedule', models.JSONField(blank=True, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_count', models.PositiveIntegerField(default=0)),
                ('is_calling_customer', models.BooleanField(default=False)),
                ('five_g_count_limit', models.IntegerField(default=0)),
                ('eligible_foc', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('gps_module_active', models.BooleanField(default=False)),
                # ('is_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GpsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_enabled', models.BooleanField()),
                ('turn_on_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('turn_off_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('mobile_no', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('next_following_date', models.DateField()),
                ('customer_type', models.CharField(choices=[('HOME', 'HOME'), ('CORPORATE', 'CORPORATE'), ('WATCHMAN', 'WATCHMAN'), ('SHOP', 'SHOP')], max_length=100)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadCustomersCancelReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeadCustomersClosedRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadCustomersReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeadCustomersStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('cancel', 'Cancel')], max_length=100)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('location_update_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('battery_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noticication_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('device_token', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('body', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Processing_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Send_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=1024, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Day_of_Visit',
            fields=[
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('week1', models.BooleanField(default=False)),
                ('week2', models.BooleanField(default=False)),
                ('week3', models.BooleanField(default=False)),
                ('week4', models.BooleanField(default=False)),
                ('week5', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=250, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('expire_time', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
