# Generated by Django 5.2.7 on 2025-10-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_branch', to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_designation', to='master.designationmaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='licence_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_emirate', to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visa_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emirate', to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='attendance_log',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_atteCUSTOMER_TYPE_CHOICESndance_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerratehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_customer_rate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customers',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_customer', to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='emirate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.locationmaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='routes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_route', to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='sales_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customers',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerratehistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='customerpricechange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcustomers',
            name='emirate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='leadcustomers',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.locationmaster'),
        ),
        migrations.AddField(
            model_name='leadcustomers',
            name='routes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='leadcustomerscancelreason',
            name='customer_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomers'),
        ),
        migrations.AddField(
            model_name='leadcustomersclosedremark',
            name='customer_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomers'),
        ),
        migrations.AddField(
            model_name='leadcustomerscancelreason',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomersreason'),
        ),
        migrations.AddField(
            model_name='leadcustomersstatus',
            name='customer_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomers'),
        ),
        migrations.AddField(
            model_name='locationupdate',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LocationUpdate_Salesman', to=settings.AUTH_USER_MODEL),
        ),
    ]
