# Generated by Django 4.0 on 2025-12-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('van_management', '0001_initial'),
        ('master', '0001_initial'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationupdate',
            name='van',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='van_management.van'),
        ),
        migrations.AddField(
            model_name='leadcustomersstatus',
            name='customer_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomers'),
        ),
        migrations.AddField(
            model_name='leadcustomersclosedremark',
            name='customer_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomers'),
        ),
        migrations.AddField(
            model_name='leadcustomerscancelreason',
            name='customer_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomers'),
        ),
        migrations.AddField(
            model_name='leadcustomerscancelreason',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadcustomersreason'),
        ),
        migrations.AddField(
            model_name='leadcustomers',
            name='emirate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='leadcustomers',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.locationmaster'),
        ),
        migrations.AddField(
            model_name='leadcustomers',
            name='routes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='guestcustomerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='guestcustomerorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster'),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customuserexportstatus',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_export_status', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customers',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_customer', to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='emirate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.locationmaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='routes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_route', to='master.routemaster'),
        ),
        migrations.AddField(
            model_name='customers',
            name='sales_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_staff', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sign', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customerratehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_customer_rate', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customerratehistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='customerpricechange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='customerexportstatus',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_export_status', to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers'),
        ),
        migrations.AddField(
            model_name='attendance_log',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_atteCUSTOMER_TYPE_CHOICESndance_log', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_branch', to='master.branchmaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_designation', to='master.designationmaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='licence_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licence_emirate', to='master.emiratemaster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_permissions', to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visa_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_emirate', to='master.emiratemaster'),
        ),
    ]
