# Generated by Django 5.2.7 on 2025-12-06 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappGuestCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=250)),
                ('building_name', models.CharField(max_length=250)),
                ('door_house_no', models.CharField(max_length=250)),
                ('floor_no', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('emirate', models.CharField(max_length=250)),
                ('mobile_no', models.CharField(blank=True, max_length=250, null=True)),
                ('whats_app', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customers',
            name='preferred_language',
            field=models.CharField(default='EN', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='whatsapp_contry_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Branch User', 'Branch User'), ('Driver', 'Driver'), ('Salesman', 'Salesman'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Customer Care', 'Customer Care'), ('Accounts', 'Accounts'), ('store_keeper', 'Store Keeper'), ('marketing_executive', 'Marketing Executive'), ('Production', 'Production'), ('owner', 'Owner'), ('Driver cum Salesman', 'Driver cum Salesman')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomerComplaints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.TextField()),
                ('status', models.CharField(default='pending', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='GuestCustomerOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('no_bottles_required', models.CharField(max_length=250)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
    ]
