# Generated by Django 5.2.7 on 2025-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_whatsappguestcustomers_customers_is_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='is_exported',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_guest',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='whatsapp_contry_code',
        ),
    ]
