# Generated by Django 5.2 on 2025-04-16 09:57

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('designation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('designation_name', models.CharField(max_length=50, unique=True)),
                ('is_exported', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('designation_name',),
            },
        ),
        migrations.CreateModel(
            name='EmirateMaster',
            fields=[
                ('emirate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_exported', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('branch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('landline', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('trn', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='master')),
                ('is_exported', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emirate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.emiratemaster')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='BranchExportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_branch_id', models.CharField(max_length=50, unique=True)),
                ('exported_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_export_status', to='master.branchmaster')),
            ],
            options={
                'ordering': ('-exported_date',),
            },
        ),
        migrations.CreateModel(
            name='DesignationExportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_designation_id', models.CharField(max_length=50, unique=True)),
                ('exported_date', models.DateTimeField(auto_now_add=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_export_status', to='master.designationmaster')),
            ],
            options={
                'ordering': ('-exported_date',),
            },
        ),
        migrations.CreateModel(
            name='EmirateExportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_emirate_id', models.CharField(max_length=50, unique=True)),
                ('exported_date', models.DateTimeField(auto_now_add=True)),
                ('emirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirate_export_status', to='master.emiratemaster')),
            ],
            options={
                'ordering': ('-exported_date',),
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=50)),
                ('is_exported', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_branch', to='master.branchmaster')),
                ('emirate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.emiratemaster')),
            ],
            options={
                'ordering': ('location_name',),
            },
        ),
        migrations.CreateModel(
            name='LocationExportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_location_id', models.CharField(max_length=50, unique=True)),
                ('exported_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_status', to='master.locationmaster')),
            ],
            options={
                'ordering': ('-exported_date',),
            },
        ),
        migrations.CreateModel(
            name='PermissionManagementTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tab_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_tabs', to='master.designationmaster')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='RouteMaster',
            fields=[
                ('route_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('route_name', models.CharField(max_length=50, unique=True)),
                ('is_exported', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_branch', to='master.branchmaster')),
            ],
            options={
                'ordering': ('route_name',),
            },
        ),
        migrations.CreateModel(
            name='RouteExportStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_route_id', models.CharField(max_length=50, unique=True)),
                ('exported_date', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_export_status', to='master.routemaster')),
            ],
            options={
                'ordering': ('-exported_date',),
            },
        ),
    ]
