# Generated by Django 5.2.7 on 2025-12-10 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customers_is_exported_and_more'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reciever_no', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='WhatsappResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_to', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
                ('created_by', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.whatsappdata')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
