# Generated by Django 5.2.7 on 2025-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdetails',
            name='hot_and_cold_dispenser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='previous_bottle_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='previous_hot_and_cold_dispenser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='previous_outstanding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='previous_outstanding_coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='previous_table_dispenser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditdetails',
            name='table_dispenser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vansaledamage',
            name='damage_from',
            field=models.CharField(choices=[('fresh_stock', 'Fresh Stock'), ('empty_can', 'Empty Can')], default='empty_can', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditdetails',
            name='bottle_outstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditdetails',
            name='outstanding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditdetails',
            name='outstanding_coupon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vansaledamage',
            name='modified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vansaledamage',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
