# Generated by Django 5.2.7 on 2025-12-10 14:45

import django.db.models.deletion
import django.utils.timezone
import sales_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_customers_is_exported_and_more'),
        ('coupon_management', '0001_initial'),
        ('invoice_management', '0001_initial'),
        ('master', '0002_whatsappdata_whatsappresponse'),
        ('product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesExtraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_needed', models.IntegerField()),
                ('no_of_coupons', models.IntegerField()),
                ('coupon_variations', models.IntegerField()),
                ('empty_bottles', models.IntegerField()),
                ('collected_bottles', models.IntegerField()),
                ('bottle_variations', models.IntegerField()),
                ('status', models.CharField(choices=[('FOC', 'FOC'), ('PENDING', 'PENDING'), ('CUSTODY', 'CUSTODY'), ('PAID', 'PAID')], max_length=10)),
                ('order_number', sales_management.models.OrderNumberField(default=None, editable=False, max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('CARD', 'CARD'), ('ONLINE', 'ONLINE')], max_length=100, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CollectionOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('online_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('collection_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_management.collectionpayment')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CollectionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_management.invoice')),
                ('collection_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.collectionpayment')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CollectionCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cheque_no', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLEARED', 'CLEARED')], default='PENDING', max_length=10)),
                ('invoices', models.ManyToManyField(to='invoice_management.invoice')),
                ('collection_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_management.collectionpayment')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('card_date', models.DateField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('card_category', models.CharField(blank=True, max_length=100, null=True)),
                ('card_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLEARED', 'CLEARED')], default='PENDING', max_length=10)),
                ('collection_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales_management.collectionpayment')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=20)),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('balance_coupons', models.IntegerField(default=0)),
                ('coupon_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_management.coupon')),
                ('coupon_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_management.coupontype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('routes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.routemaster')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OutstandingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupons', models.IntegerField(null=True)),
                ('empty_bottles', models.IntegerField(null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order_number', sales_management.models.OrderNumberField(default=None, editable=False, max_length=7, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('supply', 'supply'), ('collection', 'collection'), ('coupon_rechange', 'coupon rechange')], max_length=100, null=True)),
                ('instance_id', models.CharField(max_length=200)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'ordering': ('-instance_id',),
            },
        ),
        migrations.CreateModel(
            name='SaleEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_delivery_date', models.DateField(blank=True, null=True)),
                ('default_lt_bottle_count', models.IntegerField(blank=True, null=True)),
                ('outstanding_coupons', models.IntegerField(blank=True, default=None, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('empty_bottles', models.IntegerField(blank=True, default=None, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_taxable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_number', sales_management.models.OrderNumberField(default=None, editable=False, max_length=7, unique=True)),
                ('coupon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_management.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('extras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_management.salesextramodel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesmanSpendingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shop_in', models.DateTimeField(blank=True, null=True)),
                ('shop_out', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')], max_length=20)),
                ('transaction_category', models.CharField(choices=[('FOC', 'FOC'), ('PENDING', 'PENDING'), ('CUSTODY', 'CUSTODY'), ('PAID', 'PAID')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('order_number', sales_management.models.OrderNumberField(default=None, editable=False, max_length=7, unique=True)),
                ('created_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Transactionn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('no_of_qty', models.IntegerField(blank=True, null=True)),
                ('coupons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_management.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_management.customercoupons')),
            ],
        ),
    ]
