# Generated by Django 5.2.7 on 2025-12-10 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_customers_is_exported_and_more'),
        ('coupon_management', '0001_initial'),
        ('master', '0002_whatsappdata_whatsappresponse'),
        ('product', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competitor_name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerReturnReason',
            fields=[
                ('reason_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Customer Return Reason',
                'verbose_name_plural': 'Customer Return Reason',
                'db_table': 'customer_return_reason',
            },
        ),
        migrations.CreateModel(
            name='NonVisitReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustodyCustom',
            fields=[
                ('custody_custom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_no', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('deposit_type', models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('non_deposit', 'Non Deposit')], max_length=20, null=True)),
                ('reference_no', models.CharField(max_length=100)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustodyCustomDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit_type', models.CharField(choices=[('cash', 'Cash Deposit'), ('cheque', 'Cheque Deposit'), ('other', 'Other Deposit')], max_length=10)),
                ('deposit_form_number', models.CharField(max_length=100)),
                ('custody_custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_management.custodycustom')),
            ],
        ),
        migrations.CreateModel(
            name='CustodyCustomItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('serialnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('can_deposite_chrge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('five_gallon_water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custody_custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_management.custodycustom')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('custody_custom__created_date',),
            },
        ),
        migrations.CreateModel(
            name='Customer_Inhand_Coupons',
            fields=[
                ('cust_inhand_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_of_coupons', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cust_coupon', to='accounts.customers')),
            ],
            options={
                'ordering': ('customer',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountDeleteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_status', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCartItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customercart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque')], max_length=100, null=True)),
                ('amount_recieved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_payeble', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_number', models.CharField(max_length=100)),
                ('coupon_method', models.CharField(choices=[('digital', 'Digital'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customercoupon', to='accounts.customers')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='ChequeCouponPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=200)),
                ('cheque', models.CharField(max_length=200)),
                ('cheque_no', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('customer_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_management.customercoupon')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCouponItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon_management.newcoupon')),
                ('customer_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_management.customercoupon')),
            ],
            options={
                'ordering': ('-customer_coupon__created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCouponStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_method', models.CharField(choices=[('digital', 'Digital'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('count', models.PositiveIntegerField()),
                ('coupon_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon_management.coupontype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerCustodyStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_no', models.CharField(blank=True, max_length=400, null=True)),
                ('deposit_type', models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('non_deposit', 'Non Deposit')], max_length=20, null=True)),
                ('reference_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('serialnumber', models.CharField(blank=True, max_length=400, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('can_deposite_chrge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('five_gallon_water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approved'), ('deliverd', 'Deliverd'), ('emergency', 'Added in emergency schedule'), ('reject', 'Reject')], max_length=10)),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrdersItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='client_management.customerorders')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOtherProductCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOtherProductChargesChanges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privious_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=200, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOutstanding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('amount', 'Amount'), ('emptycan', 'Emptycan'), ('coupons', 'Coupons')], max_length=200)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOutstandingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('amount', 'Amount'), ('emptycan', 'Emptycan'), ('coupons', 'Coupons')], max_length=200)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_no', models.CharField(blank=True, max_length=500, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_type', models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('non_deposit', 'Non Deposit')], max_length=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReturnItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=520, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('customer_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_management.customerreturn')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReturnStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_no', models.CharField(blank=True, max_length=500, null=True)),
                ('deposit_type', models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('non_deposit', 'Non Deposit')], max_length=20, null=True)),
                ('reference_no', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_recieved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('collected_empty_bottle', models.PositiveIntegerField(default=0)),
                ('allocate_bottle_to_pending', models.PositiveIntegerField(default=0)),
                ('allocate_bottle_to_custody', models.PositiveIntegerField(default=0)),
                ('allocate_bottle_to_paid', models.PositiveIntegerField(default=0)),
                ('allocate_bottle_to_free', models.PositiveIntegerField(default=0)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('outstanding_amount_added', models.BooleanField(default=False)),
                ('outstanding_coupon_added', models.BooleanField(default=False)),
                ('outstanding_bottle_added', models.BooleanField(default=False)),
                ('van_stock_added', models.BooleanField(default=False)),
                ('van_foc_added', models.BooleanField(default=False)),
                ('van_emptycan_added', models.BooleanField(default=False)),
                ('custody_added', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('card_date', models.DateField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100, null=True)),
                ('card_category', models.CharField(blank=True, max_length=100, null=True)),
                ('card_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLEARED', 'CLEARED')], default='PENDING', max_length=10)),
                ('customer_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customersupply')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplyCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cheque_no', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CLEARED', 'CLEARED')], default='PENDING', max_length=10)),
                ('customer_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customersupply')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplyCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customersupply')),
                ('free_leaf', models.ManyToManyField(to='coupon_management.freeleaflet')),
                ('leaf', models.ManyToManyField(to='coupon_management.couponleaflet')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplyDigitalCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('customer_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customersupply')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplyItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customersupply')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerSupplyStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DialyCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_supply', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.routemaster')),
            ],
        ),
        migrations.CreateModel(
            name='EligibleCustomerConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moq', models.PositiveIntegerField(default=0)),
                ('days', models.PositiveIntegerField(default=0)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
        ),
        migrations.CreateModel(
            name='InactiveCustomers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inactive_days', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='MarketShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.competitors')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.produtitemmaster')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NonvisitReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supply_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customers')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.nonvisitreason')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='OutstandingAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_outstanding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customeroutstanding')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OutstandingCoupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('coupon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon_management.coupontype')),
                ('customer_outstanding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customeroutstanding')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OutstandingProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empty_bottle', models.IntegerField(default=0)),
                ('customer_outstanding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_management.customeroutstanding')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('vacation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customers')),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
