# Generated by Django 5.2.7 on 2025-10-24 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Reason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_change',
            fields=[
                ('note', models.TextField(blank=True, null=True)),
                ('order_change_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_quantity', models.IntegerField()),
                ('change_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order_return',
            fields=[
                ('note', models.TextField(blank=True, null=True)),
                ('order_return_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('returned_quantity', models.IntegerField()),
                ('return_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('noof_empty_bottles_returned', models.CharField(blank=True, max_length=20, null=True)),
                ('required_emptybottles', models.BooleanField(blank=True, default=False, null=True)),
                ('noof_empty_bottles_reqrd', models.CharField(blank=True, max_length=20, null=True)),
                ('empty_bottle_amnt', models.CharField(blank=True, max_length=20, null=True)),
                ('total_net_amnt', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_option', models.CharField(choices=[('online payment', 'Online payment'), ('cash on delivery', 'Cash on delivery')], max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customers')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
